Fix deprecated error in case $post=null in the function the_company_twitter(). This way, if $post=null, it will not run the second test with strlen().
Error: Deprecated: strlen():
Passing null to parameter #1 ($string) of type string is deprecated in /wp-job-manager/wp-job-manager-template.php on line 1137